backend:
  name: git-gateway
  repo: milanhybner/sokolsestajovice.cz
  branch: gh-pages # Branch to update (optional; defaults to master)

media_folder: "images" # Media files will be stored in the repo under images/uploads
public_folder: "images"

collections:
  - name: "clanky" # Used in routes, e.g., /admin/collections/blog
    label: "Články" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Název", name: "title", widget: "string"}
      - {label: "Výcuc", name: "excerpt", widget: "string"}
      - {label: "Název do adresy - krátký bez interpunkce a mezer", name: "slug", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Obrázek", name: "image", widget: "image", required: false}
      - {label: "Text obsahu", name: "body", widget: "markdown"}